"""
C2PA Content Credentials 检测器

检测图像中是否嵌入了 C2PA 数字签名清单:
  - JPEG: 检查 JUMBF box (0x4A554D42) 在 App11 段中
  - PNG:  检查 c2pa/iTXt chunk
  - 解析 manifest 获取: 生成工具、时间戳、签名机构、内容来源

C2PA (Coalition for Content Provenance and Authenticity)
规范: https://c2pa.org/specifications/specifications/2.1/
"""

import struct
import json
from dataclasses import dataclass, field
from typing import Any


@dataclass
class C2PAResult:
    """C2PA 检测结果"""
    detected: bool = False
    manifest_count: int = 0
    issuer: str | None = None          # 签发机构
    generator: str | None = None       # 生成工具 (如 DALL-E, Photoshop, Firefly)
    generated_at: str | None = None    # 生成时间
    content_source: str | None = None  # 内容来源描述
    signature_valid: bool | None = None  # 签名是否有效
    raw_manifest: str | None = None    # 原始 JSON manifest
    details: list[str] = field(default_factory=list)


class C2PADetector:
    """C2PA Content Credentials 检测器"""

    name = "c2pa_content_credentials"
    version = "0.1.0"

    # JUMBF magic bytes (出现在 JPEG App11 段中)
    JUMBF_MAGIC = b'\x4A\x55\x4D\x42'  # "JUMB"
    C2PA_BOX_UUID = b'\x63\x32\x70\x61'  # "c2pa"
    C2PA_MANIFEST_STORE_UUID = b'\x63\x32\x70\x73'  # "c2ps"

    def detect(self, image_data: bytes, filename: str = "") -> C2PAResult:
        """检测图像中的 C2PA 清单"""
        ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""

        if ext in ("jpg", "jpeg"):
            return self._detect_jpeg(image_data)
        elif ext == "png":
            return self._detect_png(image_data)
        else:
            return self._detect_generic(image_data)

    def _detect_jpeg(self, data: bytes) -> C2PAResult:
        """解析 JPEG 文件中的 C2PA JUMBF box"""
        result = C2PAResult()
        pos = 2  # 跳过 SOI marker

        while pos < len(data) - 4:
            if data[pos] != 0xFF:
                pos += 1
                continue

            marker = data[pos + 1]
            if marker in (0xD8, 0x00):  # SOI / padding
                pos += 2
                continue
            if marker == 0xD9:  # EOI
                break

            # 读取段长度
            if pos + 4 > len(data):
                break
            seg_len = struct.unpack(">H", data[pos+2:pos+4])[0]

            # App11 段通常包含 C2PA 数据
            if marker == 0xEB:  # App11
                seg_data = data[pos+4:pos+2+seg_len]
                result = self._parse_jumbf_box(seg_data, result)
                if result.detected:
                    return result

            pos += 2 + seg_len

        return result

    def _parse_jumbf_box(self, data: bytes, result: C2PAResult) -> C2PAResult:
        """解析 JUMBF box 结构, 提取 C2PA manifest"""
        # 搜索 JUMBF magic
        idx = data.find(self.JUMBF_MAGIC)
        if idx < 0:
            return result

        result.detected = True
        result.details.append("检测到 C2PA JUMBF 容器")

        # 尝试查找 c2pa manifest store
        c2pa_idx = data.find(b'"c2pa_manifest"')
        if c2pa_idx > 0:
            result.manifest_count += 1
            result.details.append("发现 C2PA Manifest 清单")

        # 尝试提取 JSON 内容
        try:
            json_start = data.find(b'{')
            if json_start > 0:
                json_end = data.rfind(b'}')
                if json_end > json_start:
                    json_str = data[json_start:json_end+1].decode("utf-8", errors="replace")
                    result.raw_manifest = json_str
                    manifest = json.loads(json_str)

                    # 提取关键字段
                    result.generator = manifest.get("claim_generator") or \
                                       (manifest.get("assertions", [{}])[0].get("data", {}).get("generator"))
                    result.issuer = manifest.get("issuer") or \
                                    manifest.get("signature_info", {}).get("issuer")
                    result.content_source = "C2PA 认证"
                    result.signature_valid = manifest.get("signature_info") is not None
                    result.details.append(f"签发机构: {result.issuer}" if result.issuer else None)
                    result.details.append(f"生成工具: {result.generator}" if result.generator else None)
                    result.details = [d for d in result.details if d is not None]
        except Exception:
            pass

        # 尝试提取 c2pa assertion
        assertion_idx = data.find(b'c2pa.assertions')
        if assertion_idx > 0:
            result.details.append("包含 C2PA Assertions（内容声明）")

        # 查找常见的 AI 生成标签
        ai_keywords = [b'AI-Generated', b'AIGenerated', b'generative-ai',
                       b'Adobe Firefly', b'DALL-E', b'Stable Diffusion',
                       b'Midjourney', b'Generated by AI']
        for kw in ai_keywords:
            if kw in data:
                gen_name = kw.decode("utf-8")
                result.details.append(f"检测到 AI 生成声明: {gen_name}")
                result.generator = result.generator or gen_name
                break

        return result

    def _detect_png(self, data: bytes) -> C2PAResult:
        """解析 PNG 文件中的 C2PA chunk"""
        result = C2PAResult()
        pos = 8  # 跳过 PNG signature

        while pos < len(data) - 12:
            chunk_len = struct.unpack(">I", data[pos:pos+4])[0]
            chunk_type = data[pos+4:pos+8].decode("ascii", errors="replace")

            # C2PA 数据存储在 iTXt 或 zTXt chunk 中
            if chunk_type in ("iTXt", "zTXt", "tEXt"):
                keyword_end = data.index(b'\x00', pos+8)
                keyword = data[pos+8:keyword_end].decode("latin-1", errors="replace")
                if "c2pa" in keyword.lower():
                    result.detected = True
                    result.manifest_count += 1
                    result.details.append(f"PNG 中发现 C2PA chunk: {keyword}")
                    # 尝试解析内容
                    content_start = keyword_end + 1
                    if chunk_type == "zTXt":
                        content_start += 1
                    content_str = data[content_start:pos+8+chunk_len].decode("utf-8", errors="replace")
                    result.raw_manifest = content_str[:500]

            if chunk_type == "IEND":
                break

            pos += 12 + chunk_len

        return result

    def _detect_generic(self, data: bytes) -> C2PAResult:
        """通用检测: 搜索 C2PA 相关字节模式"""
        result = C2PAResult()

        patterns = [
            (b'"c2pa_manifest"', "C2PA Manifest 清单"),
            (b'c2pa-rs', "C2PA Rust 签名"),
            (b'data_types\\":\\"c2pa', "C2PA 数据类型引用"),
            (b'claim_generator', "C2PA Claim Generator"),
            (b'content_credentials', "Content Credentials 凭证"),
            (b'digital_source_type', "C2PA 数字来源类型"),
        ]

        for pattern, description in patterns:
            if pattern in data:
                result.detected = True
                result.manifest_count += 1
                result.details.append(description)

        if result.detected:
            # 尝试解析 JSON manifest
            try:
                search_pos = 0
                while True:
                    c2pa_pos = data.find(b'"c2pa', search_pos)
                    if c2pa_pos < 0:
                        break
                    brace_start = data.rfind(b'{', max(0, c2pa_pos-500), c2pa_pos+50)
                    brace_count = 0
                    pos = brace_start
                    while pos < len(data):
                        if data[pos:pos+1] == b'{': brace_count += 1
                        elif data[pos:pos+1] == b'}':
                            brace_count -= 1
                            if brace_count == 0:
                                json_segment = data[brace_start:pos+1].decode("utf-8", errors="replace")
                                result.raw_manifest = result.raw_manifest or json_segment
                                try:
                                    manifest = json.loads(json_segment)
                                    result.generator = manifest.get("claim_generator")
                                    result.issuer = manifest.get("issuer")
                                except:
                                    pass
                                break
                        pos += 1
                    search_pos = c2pa_pos + 4

            except Exception:
                pass

        return result


# 便捷函数
def check_c2pa(image_data: bytes, filename: str = "") -> C2PAResult:
    detector = C2PADetector()
    return detector.detect(image_data, filename)
