"""
GB 45438—2025 标识检测器

国家标准《人工智能 生成内容标识方法》规定的 AI 生成内容标识:
  - 显式标识: 文本中 "@AI生成" 标记 / 图像水印 / 音频提示音
  - 隐式标识: 元数据字段 (XMP/IPTC/EXIF)
  - 必备字段: 生成模型名称、生成时间、内容哈希、版权声明

参考: GB 45438—2025 / TC260-003
"""

import json
import re
import struct
from dataclasses import dataclass, field
from PIL import Image
import io


@dataclass
class GB45438Result:
    """GB 45438—2025 标识检测结果"""
    detected: bool = False
    has_explicit_mark: bool = False    # 显式标识 (水印/标记文字)
    has_implicit_mark: bool = False    # 隐式标识 (元数据)
    generator: str | None = None       # 生成模型
    generated_at: str | None = None    # 生成时间
    copyright_info: str | None = None  # 版权声明
    compliance_level: str = "none"     # none / partial / full
    details: list[str] = field(default_factory=list)


class GB45438Detector:
    """GB 45438—2025 标识检测器"""

    name = "gb45438_2025_identifier"
    version = "0.1.0"

    # GB 45438 规定的元数据字段名 (XMP/exif)
    GB_METADATA_FIELDS = [
        "AIGCGenerator", "AIGenerationTime", "AIGCContentHash",
        "AIGCCopyright", "GB45438Compliance", "AIVersion",
        "GenerativeModel", "AIGenerated", "SyntheticContent",
    ]

    # 显式标识文本模式
    EXPLICIT_PATTERNS = [
        r"@AI生成", r"@AIGC", r"\[AI生成\]", r"《AI生成》",
        r"本内容由.*AI.*生成", r"Generated by AI",
        r"AI-Generated Content", r"Synthetic Content",
        r"人工智能生成", r"AIGC标识",
    ]

    def detect_text(self, text: str) -> GB45438Result:
        """检测文本中的 GB 45438 标识"""
        result = GB45438Result()

        for pattern in self.EXPLICIT_PATTERNS:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                result.has_explicit_mark = True
                result.details.append(f"发现显式标识: {matches[0]}")

        if result.has_explicit_mark:
            result.detected = True
            result.compliance_level = "partial"
            # 检查是否包含更多合规字段
            has_model = any(kw in text for kw in ["生成模型", "generator", "Model:"])
            has_time = any(kw in text for kw in ["生成时间", "generated", "timestamp"])
            if has_model and has_time:
                result.compliance_level = "full"
                result.details.append("符合 GB 45438 全量标识要求")
            else:
                result.details.append("缺少生成模型/时间等必填字段，建议补充")

        return result

    def detect_image(self, image_data: bytes) -> GB45438Result:
        """检测图像中的 GB 45438 标识 (XMP/EXIF/IPTC 元数据)"""
        result = GB45438Result()

        try:
            img = Image.open(io.BytesIO(image_data))
            metadata = img.info or {}

            # 检查 XMP 数据
            xmp_data = metadata.get("xmp", "") or metadata.get("xml", "")
            if isinstance(xmp_data, bytes):
                xmp_data = xmp_data.decode("utf-8", errors="replace")

            for field in self.GB_METADATA_FIELDS:
                if field.lower() in metadata or field in str(metadata):
                    result.has_implicit_mark = True
                    result.detected = True
                    result.details.append(f"隐式标识字段: {field}")
                if field in xmp_data:
                    result.has_implicit_mark = True
                    result.detected = True
                    result.details.append(f"XMP 隐式标识: {field}")

            # 从 EXIF 提取
            exif = img.getexif() if hasattr(img, "getexif") else {}
            for tag_id, value in exif.items():
                str_val = str(value)
                for field in self.GB_METADATA_FIELDS:
                    if field.lower() in str_val.lower():
                        result.has_implicit_mark = True
                        result.detected = True
                        result.details.append(f"EXIF 标识: {field}={value}")

            # 从元数据提取生成器信息
            for key, value in metadata.items():
                key_lower = key.lower()
                if "generator" in key_lower or "aigc" in key_lower:
                    result.generator = result.generator or str(value)
                    result.has_implicit_mark = True
                    result.detected = True
                if "time" in key_lower or "date" in key_lower:
                    result.generated_at = result.generated_at or str(value)
                if "copyright" in key_lower or "rights" in key_lower:
                    result.copyright_info = result.copyright_info or str(value)

            # 检查 AI 生成标记 (Adobe Firefly, Midjourney 等)
            descriptions = [
                str(metadata.get(k, "")) for k in metadata
                if "description" in str(k).lower() or "comment" in str(k).lower()
            ]
            for desc in descriptions:
                for kw in ["AI-generated", "AI generated", "Generated by AI",
                           "Midjourney", "DALL-E", "Stable Diffusion",
                           "Adobe Firefly", "Synthetic"]:
                    if kw.lower() in desc.lower():
                        result.details.append(f"发现 AI 生成描述: {desc[:80]}")
                        result.detected = True
                        break

            # 判定合规等级
            if result.detected:
                result.compliance_level = "partial"
                if result.has_implicit_mark and result.generator and result.generated_at:
                    result.compliance_level = "full"
                    result.details.append("符合 GB 45438 全量隐式标识要求")

        except Exception:
            pass

        return result

    def detect_audio_metadata(self, audio_bytes: bytes, format: str = "wav") -> GB45438Result:
        """检测音频文件的元数据标识 (WAV INFO / MP3 ID3 tags)"""
        result = GB45438Result()

        if format == "mp3" and len(audio_bytes) > 128:
            # 检查 ID3v1 tag (最后 128 字节)
            tail = audio_bytes[-128:]
            if tail[:3] == b'TAG':
                comment = tail[97:127].decode("latin-1", errors="replace").strip('\x00')
                for field in self.GB_METADATA_FIELDS:
                    if field.lower() in comment.lower():
                        result.detected = True
                        result.has_implicit_mark = True
                        result.details.append(f"ID3 标识: {field}")

        elif format == "wav" and len(audio_bytes) > 44:
            # 检查 WAV INFO chunk
            try:
                pos = 12  # 跳过 RIFF header
                while pos < len(audio_bytes) - 8:
                    chunk_id = audio_bytes[pos:pos+4].decode("ascii", errors="replace")
                    chunk_size = struct.unpack("<I", audio_bytes[pos+4:pos+8])[0]
                    if chunk_id == "LIST":
                        sub_data = audio_bytes[pos+12:pos+8+chunk_size]
                        for field in self.GB_METADATA_FIELDS:
                            if field.encode() in sub_data:
                                result.detected = True
                                result.has_implicit_mark = True
                                result.details.append(f"WAV INFO 标识: {field}")
                        break
                    if chunk_id == "data":
                        break
                    pos += 8 + chunk_size
            except Exception:
                pass

        return result


# 便捷函数
def check_gb45438_text(text: str) -> GB45438Result:
    return GB45438Detector().detect_text(text)

def check_gb45438_image(image_data: bytes) -> GB45438Result:
    return GB45438Detector().detect_image(image_data)
